### ISSUE TITLE
Performance-Customized ETW With Array Parameters

### ISSUE THREAD

**Issue by jcdickinson** [microsoft/dotnet-samples#30]
_Aside: I'm really looking for how to deal with this for EventProvider+manifests, but it looks like EventSource and EventProvider work the same way in this specific scenario._

I can't find documentation _anywhere_ (GitHub, MSDN, the works) on this. How would you approach implementing this method?

```
[Event]
public void Foo(string[] vals) { ... }
```

Or this one?

```
[Event]
public void Foo(int[] vals) { ... }
```

The ETW examples don't demonstrate this scenario. The string list necessitates the following "classic" manifest, for example:

```
<template tid="t23EFDE6D13D62A45">
    <data inType="win:UInt16" name="vals.Count" />
    <struct name="vals" count="vals.Count">
        <data inType="win:UInt16" name="vals.Length" />
        <data inType="win:UnicodeString" length="vals.Length" name="vals" />
    </struct>
</template>
```

This means that the buffer has to effectively follow that schema. My best guess is the following:

```
// 0: vals.Count
// 1: vals
EventData* descr = stackalloc EventData[2];

var valsLen = Math.Min(vals.Length, 20);
EventData* valsDescr = stackalloc EventData[valsLen * 2];

descr[0].DataPointer = new IntPtr(checked((ushort)vals.Length));
descr[0].Size = sizeof(ushort);

try
{
    // n + 0: val.Length
    // n + 1: val
    var valsLength = 0;
    for (var i = 0; i < vals.Length; i++)
    {
        var val = vals[i];
        if (val != null)
        {
            var ii = i * 2;
            var ij = ii + 1;

            valsDescr[ij].DataPointer = Marshal.StringToHGlobalUni(val);
            valsDescr[ij].Size = (val.Length + 1) * sizeof(char);

            valsDescr[ii].DataPointer = new IntPtr(checked((ushort)valsDescr[ij].Size));
            valsDescr[ii].Size = sizeof(ushort);

            valsLength += valsDescr[ij].Size;
        }
    }

    descr[1].DataPointer = new IntPtr(valsDescr);
    descr[1].Size = valsLength;

    // Write Event
}
finally
{
    for (var i = 1; i < vals.Length; i++)
    {
        var ptr = valsDescr[1 + i * 2].DataPointer;
        if (ptr != IntPtr.Zero) Marshal.FreeHGlobal(ptr);
    }
}
```

Any chance we could have the examples expanded to include `int[]` (fixed-length item arrays) and `string[]` (variable-length item arrays)?

**Comment by weltkante** [comment]
Unrelated to your question, but pinning the strings instead of copying them might be more performant.

**Comment by jcdickinson** [comment]
@weltkante I tried, but the problem is that you can't used `fixed` with ref types - the automagic string-to-char\* seems to break as soon as you involve arrays.

**Comment by weltkante** [comment]
@jcdickinson You can pin manually using [`GCHandle.Alloc`](https://msdn.microsoft.com/en-us/library/1246yz8f) and [`GCHandle.AddrOfPinnedObject`](https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.gchandle.addrofpinnedobject) on each string instead of the `fixed` language statement. Its a struct so no actual allocations happen and you can optimize away the array-of-GCHandles too:
```csharp
private unsafe void Foo(string[] vals)
{
    var handles = stackalloc GCHandle[vals.Length];
    try
    {
        for (int i = 0; i < vals.Length; i++)
        {
            handles[i] = GCHandle.Alloc(vals[i], GCHandleType.Pinned);
            var pointerToFirstCharOfString = handles[i].AddrOfPinnedObject();
            // ...
        }
    }
    finally
    {
        for (int i = 0; i < vals.Length; i++)
            if (handles[i].IsAllocated) // if we are leaving the try-block via exception some handles may not have been assigned yet and calling Free() on them would mask the original exception by throwing a different one
                handles[i].Free();
    }
}
```

Sorry for leading the question off-topic.
